---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/appointments":
    get:
      summary: list appointments
      responses:
        '200':
          description: successful
    post:
      summary: create appointment
      responses:
        '200':
          description: successful
  "/api/v1/appointments/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update appointment
      responses:
        '200':
          description: successful
    put:
      summary: update appointment
      responses:
        '200':
          description: successful
    delete:
      summary: delete appointment
      responses:
        '200':
          description: successful
  "/appointments":
    post:
      summary: create appointment
      responses:
        '200':
          description: successful
  "/api/v1/appointments/{user_id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list appointments
      responses:
        '200':
          description: successful
  "/api/v1/doctors":
    get:
      summary: list doctors
      responses:
        '200':
          description: successful
  "/api/v1/doctors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show doctor
      responses:
        '200':
          description: successful
  "/api/v1/registrations":
    post:
      summary: create registration
      tags:
      - Registrations
      parameters: []
      responses:
        '201':
          description: registration created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_digest:
                  type: string
              required:
              - name
              - email
              - password
              - password_digest
  "/api/v1/sessions":
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/api/v1/logout":
    delete:
      summary: delete session
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3001/
